// <auto-generated />
using HRIS.WebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HRIS.WebAPI.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRIS.WebAPI.Models.Master_Data.Branch", b =>
                {
                    b.Property<int>("BranchID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(15);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15);

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("BranchID");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("HRIS.WebAPI.Models.Master_Data.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BranchID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(15);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15);

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("DepartmentID");

                    b.HasIndex("BranchID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HRIS.WebAPI.Models.Master_Data.Department", b =>
                {
                    b.HasOne("HRIS.WebAPI.Models.Master_Data.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
